### ISSUE TITLE
error

### ISSUE THREAD

**Issue by drduan** [qinyuanpei/HttpServer#1]
CSC: error CS2001: Source file `TcpServer.cs' could not be found

**Comment by qinyuanpei** [comment]
这个类我还没有写完，所以在正式发布的项目代码中没有这个文件，因为这是我第四篇相关博客中涉及到的内容，即两种改进的设计HTTP服务器的方案，正式代码还没有写完，如果需要我尽快更新到这个仓库里！

**Comment by drduan** [comment]
好的 谢谢博主~

**Comment by joindn** [comment]
博主更新呀，星星送上了
