### ISSUE TITLE
直接下载源码无法使用Post提交

### ISSUE THREAD

**Issue by wangq2008** [qinyuanpei/HttpServer#13]
使用Post提交， var contentType = GetHeader(RequestHeaders.ContentType); 异常

**Comment by qinyuanpei** [comment]
收到，下班后我去看看是什么原因:smile:

**Comment by qinyuanpei** [comment]
已经查证是栈溢出的错误，正在找原因中

**Comment by RLYKing** [comment]
我也遇到同样的问题，
public string GetHeader(RequestHeaders header)
 {
            return GetHeader(header);
}
无限递归

**Comment by RLYKing** [comment]
问题已经解决
public string GetHeader(RequestHeaders header)
{
return this.GetHeader(header);
}
访问基类的GetHeader函数，忘记使用this指针，导致无限递归，堆栈溢出。

**Comment by ananck** [comment]
请问post body 从怎么获取?

**Comment by starnc** [comment]
我注释掉了OnPost里的这行代码，post请求可用，response.Headers["Server"] = "ExampleServer";

**Comment by qinyuanpei** [comment]
已修复Post时空引用的错误
