### ISSUE TITLE
get方法获取parm为null

### ISSUE THREAD

**Issue by starnc** [qinyuanpei/HttpServer#20]
get方法获取parm为null

**Comment by starnc** [comment]
> get方法获取parm为null

HTTPServerLib.HttpRequest中的代码进行如下修改

            //Request "GET"
            if (this.Method == "GET")
            {
                this.Body = GetRequestBody(rows);
                var isUrlencoded = Uri.UnescapeDataString(first[1]).Contains('?');
                if (isUrlencoded) this.Params = GetRequestParameters(Uri.UnescapeDataString(first[1]).Split('?')[1]);
            }

**Comment by qinyuanpei** [comment]
已修复
