### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NewFuture** [qinyuanpei/HttpServer#3]
fork 了一份代码
然后在现在的基础上重构了下 https://github.com/NewFuture/HttpServer/tree/future

没有License然后加了一份MIT的License， 如有不妥 ，告诉我， 我重写一份:smile:

**Comment by qinyuanpei** [comment]
Nothing is true, Everything is permitted。如果我写的代码对别人而言，还有点用的话，这是我的荣幸啊，哈哈😄
