### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by qinyuanpei** [qinyuanpei/HttpServer#4]
关于CDN有什么好的思路来解决呢？通过网络来返回字节流然后发送到客户端吗？

**Comment by NewFuture** [comment]
这和CDN没关系不大吧?

**Comment by qinyuanpei** [comment]
比如说你的静态页面中引用了一个CDN加速的资源，那么对服务器来说，它是否需要先从这个CDN指向服务器去下载资源呢？

**Comment by NewFuture** [comment]
服务器不负责这个工作，这是浏览器干的事情(向CDN服务器请求资源)，

如果是代理性质的CDN服务器，而且没有这个资源，需要回源获取资源

**Comment by qinyuanpei** [comment]
每天学一点儿
