### ISSUE TITLE
HttpRequest请求头部Content加入数据在BaseHeader.GetRequestParams方法写法有误

### ISSUE THREAD

**Issue by Aikenwu** [qinyuanpei/HttpServer#6]
原来写法：

 /// <summary>
        /// 从内容中解析请求参数并返回一个字典
        /// </summary>
        /// <param name="content">使用&连接的参数字符串</param>
        /// <returns>如果存在参数则返回参数否则返回null</returns>
        protected Dictionary<string, string> GetRequestParams(string content)
        {
            //防御编程
            if (string.IsNullOrEmpty(content))
                return null;

            //按照&对字符进行分割
            string[] reval = content.Split('&');
            if (reval.Length <= 0)
                return null;

            //将结果添加至字典
            Dictionary<string, string> dict = new Dictionary<string, string>();
            foreach (string val in reval)
            {
                string[] kv = val.Split('=');
                if (kv.Length <= 1)
                    dict.Add(kv[0], "");
                    dict.Add(kv[0], kv[1]);
            }

            //返回字典
            return dict;
        }

kv会报错超出索引。忘记写else了吧。强烈建议if，else都上{ }，要不然不容易看出来。
ps：dll挺好用的，已经尝试运用在项目中。

**Comment by qinyuanpei** [comment]
[捂脸]的确忘记写else了，我天
