### ISSUE TITLE
Request Content头部加入内容读取问题

### ISSUE THREAD

**Issue by Aikenwu** [qinyuanpei/HttpServer#7]
在一个项目使用HttpClient.SendAsync，使用post请求，并且在Content头部加入数据及部分内容。
1.使用你的项目运行调试，能够得到如下content结果：
POST /api/xxx/xxx HTTP/1.1
sign: 3FB30070C49074068CFDE5C852D3D0D9
Accept: application/json
KeepAlive: true
Content-Type: application/json
Host: 172.16.40.78:4050
Content-Length: 127
Expect: 100-continue
Connection: Keep-Alive

{"Id":"aaa"}

这样能够得到Params值，及{"Id":"aaa"}。

2.将你的项目debug或者release到我的项目中引用，运行调试则得到如下结果：
POST /api/xxx/xxx HTTP/1.1
sign: 3FB30070C49074068CFDE5C852D3D0D9
Accept: application/json
KeepAlive: true
Content-Type: application/json
Host: 172.16.40.78:4050
Content-Length: 127
Expect: 100-continue
Connection: Keep-Alive

无法读取到{"Id":"aaa"} 这个数据。确认过写法一致，使用方法，端口均保持一致，且尝试使用postman，得到内容相同。

你的项目本身独自运行没有任何问题。现在问题是加入到我的项目中，content读不到最后的数据问题？
不知道问题出在何处？能够有解决思路提供？ 感谢。

**Comment by Aikenwu** [comment]
找到了解决方案。原因是Stream和NetworkStream。
        /// <summary>
        /// 处理客户端请求
        /// </summary>
        /// <param name="handler">客户端Socket</param>
        private void ProcessRequest(TcpClient handler)
        {
            //处理请求
            Stream clientStream = handler.GetStream();
            NetworkStream netStream = handler.GetStream();
            //处理SSL
            if (serverCertificate != null) clientStream = ProcessSSL(clientStream);
            if (clientStream == null) return;

            //构造HTTP请求
            HttpRequest request = new HttpRequest(netStream);
            request.Logger = Logger;

            //构造HTTP响应
            HttpResponse response = new HttpResponse(clientStream);
            response.Logger = Logger;

            //处理请求类型
            switch (request.Method)
            {
                case "GET":
                    OnGet(request, response);
                    break;
                case "POST":
                    OnPost(request, response);
                    break;
                default:
                    OnDefault(request, response);
                    break;
            }
            clientStream.Dispose();//释放数据流中的数据
            handler.Close();//释放TcpClient实例
        }

HttpRequest构造函数传入的NetworkStream，这样就能读取出值。
但又遇到另外一个问题，debug的dll能正常运行，release就不能读取出值。
是否由于编码方式造成？我已经改成utf8编码。

**Comment by qinyuanpei** [comment]
我晚上回去看看具体是什么原因，我觉得这个轮子完不成了啊(😭)

**Comment by Aikenwu** [comment]
我觉得是我的项目问题，因为我是用task.run 来启动sever的监听，主线程执行form窗体任务，然后使用await httpclient.sendasync发送请求信息。整个server监听没问题，能够得到头部信息，但头部数据有时候能接收，有时候不能接收。如果打上断点，就能够准确接收。
我尝试TcpClient 的Nodelay设置为true，或者采用AcceptTcpClientAsync，仍未解决。
因此放弃采用头部数据，采用urlencode，post数据，再转换为json解析。

**Comment by qinyuanpei** [comment]
问题解决！是HttpRequest从NetStream里读取数据时出现错误，读取的报文内容不完整导致Params属性为空，该issue已修复！
